"""add page banners table

Revision ID: 0568d5d28e4f
Revises: 273cdcfb580c
Create Date: 2026-07-13 10:39:10.901671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0568d5d28e4f'
down_revision: Union[str, None] = '273cdcfb580c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_banners',
    sa.Column('about_banner_url', sa.String(), nullable=True),
    sa.Column('piglets_banner_url', sa.String(), nullable=True),
    sa.Column('breeding_banner_url', sa.String(), nullable=True),
    sa.Column('gallery_banner_url', sa.String(), nullable=True),
    sa.Column('location_banner_url', sa.String(), nullable=True),
    sa.Column('contact_banner_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_banners')
    # ### end Alembic commands ###
