"""initial schema

Revision ID: ca04720ef3b8
Revises: 
Create Date: 2026-07-12 22:28:11.302375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca04720ef3b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_page',
    sa.Column('story_en', sa.Text(), nullable=False),
    sa.Column('story_ne', sa.Text(), nullable=False),
    sa.Column('practices_en', sa.Text(), nullable=False),
    sa.Column('practices_ne', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('owner_message_en', sa.Text(), nullable=False),
    sa.Column('owner_message_ne', sa.Text(), nullable=False),
    sa.Column('owner_photo_url', sa.String(), nullable=True),
    sa.Column('farm_photo_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('albums',
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_ne', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_info',
    sa.Column('farm_name_en', sa.String(), nullable=False),
    sa.Column('farm_name_ne', sa.String(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ne', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('address_en', sa.String(), nullable=False),
    sa.Column('address_ne', sa.String(), nullable=False),
    sa.Column('hours_en', sa.Text(), nullable=False),
    sa.Column('hours_ne', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('facebook_url', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('tiktok_url', sa.String(), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('highlights',
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_ne', sa.String(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ne', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_page',
    sa.Column('hero_title_en', sa.String(), nullable=False),
    sa.Column('hero_title_ne', sa.String(), nullable=False),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=False),
    sa.Column('hero_subtitle_ne', sa.Text(), nullable=False),
    sa.Column('hero_image_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pigs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('listing_type', sa.Enum('piglet', 'breeding', name='listing_type'), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='pig_gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('available', 'reserved', 'sold', name='pig_status'), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ne', sa.Text(), nullable=False),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_images',
    sa.Column('album_id', sa.UUID(), nullable=True),
    sa.Column('caption_en', sa.Text(), nullable=True),
    sa.Column('caption_ne', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquiries',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('pig_id', sa.UUID(), nullable=True),
    sa.Column('interest', sa.String(), nullable=True),
    sa.Column('quantity', sa.String(), nullable=True),
    sa.Column('preferred_contact_method', sa.Enum('phone', 'email', 'whatsapp', name='preferred_contact_method'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'closed', name='inquiry_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pig_id'], ['pigs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiries')
    op.drop_table('gallery_images')
    op.drop_table('pigs')
    op.drop_table('home_page')
    op.drop_table('highlights')
    op.drop_table('farm_info')
    op.drop_table('albums')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('about_page')
    # ### end Alembic commands ###
