"""add hero video url to home page

Revision ID: f5ac03e4902f
Revises: e7eab4ad1c2e
Create Date: 2026-07-13 16:36:25.880543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ac03e4902f'
down_revision: Union[str, None] = 'e7eab4ad1c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_page', sa.Column('hero_video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_page', 'hero_video_url')
    # ### end Alembic commands ###
